### ISSUE TITLE
Adding a Hill-Cipher Encryption/Decryption Algorithm for ASCII in Python.

### ISSUE THREAD

**Issue by muhammad-mobeen** [samiullahsaleem/cyberblock#364]
Hill-Cipher Encryption/Decryption Algorithm for ASCII in Python.

**Comment by samiullahsaleem** [comment]
Jurt create a pull request with the solution. I will merge that

**Comment by muhammad-mobeen** [comment]
> Jurt create a pull request with the solution. I will merge that

Done!

**Comment by samiullahsaleem** [comment]
Thank you for your contribution! I am merging it.
