### ISSUE TITLE
JavaScript - CrashCourse code And Some popular  c++ / c# programs

### ISSUE THREAD

**Issue by SyedSaad-07** [samiullahsaleem/cyberblock#392]
### About JavaScript
A crashcourse JS file which includes the implementation of many concepts in JS.

### About c++ and c#
There are some interesting c++ and c# codes.

**Comment by samiullahsaleem** [comment]
Create a pull request with changes. I will merge it.

**Comment by SyedSaad-07** [comment]
Ok, that's great.
