### ISSUE TITLE
JavaScript Function 

### ISSUE THREAD

**Issue by ShehrozIrfan** [samiullahsaleem/cyberblock#48]
Write a function that will take a parameter, let say `num` so if the `num` is 100 the function would return 101 and if the number is 101 the function would return 100.
Note: Don't use any conditionals!

**Comment by ShehrozIrfan** [comment]
Hey!
Anyone here who can assign this to me?

**Comment by samiullahsaleem** [comment]
I have assigned you but you can simply create pull request for it

**Comment by ShehrozIrfan** [comment]
@samiullahsaleem 
okay.
