### ISSUE TITLE
Update Java in README.md to the next line using markdown language

### ISSUE THREAD

**Issue by gupta-soham** [samiullahsaleem/cyberblock#90]

**Comment by heysagnik** [comment]
Can I work on this 😅 ?

**Comment by samiullahsaleem** [comment]
create a pull request and correct the issue. 
I will merge that

**Comment by samiullahsaleem** [comment]
> Can I work on this 😅 ?

Yes You can!
Create a pull request and correct the issue.
I will merge your request

**Comment by samiullahsaleem** [comment]
The issue has been resolved by @heysagnik

**Comment by heysagnik** [comment]
Please can you add hacktoberfest-accepted label 🏷️🤧
